apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz
  template:
    metadata:
      labels:
        app: xyz
    spec:
      containers:
      - name: xyz
        image: mahoro01/xyztechnologies:1.0
        ports:
        - containerPort: 8080
